import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import styles from "./layout.module.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Ga-linda's Closet",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={styles.body}>
      <body
        className={`${styles.body} ${geistSans.variable} ${geistMono.variable}`}
      >
        <header className={styles.header}>
          <Link href="/">
            <h2>Ga-linda's Closet</h2>
          </Link>
        </header>
        <main className={styles.main}>{children}</main>
        <footer className={styles.footer}>
          Made with love by Joshua Martin from data by friends.
        </footer>
      </body>
    </html>
  );
}
